#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        #"C-w")
                #nitrogen --save --set-zoom-fill "$file" ;;
        "C-w")
				#plasma-apply-wallpaperimage "$file" ;;
				feh --bg-fill "$file" ;;
        esac
done
