# ~/.config/fuzzel/fuzzel.ini
[main]
font=JetBrainsMono Nerd Font:size=12
width=60
lines=13
icon-theme=Papirus
icons-enabled=yes
line-height=28
[colors]
background=121213ff
text=c1c1c1ff
selection=414142ff
selection-text=89b4faff
match=D35A5Aff
border=252526ff
prompt=c1c1c1ff
input=c1c1c1ff
[border]
width=2
radius=10

[key-bindings]
delete-line-forward=none
prev=Up Control+k
next=Down Control+j
