set -g prefix C-Space
unbind C-b
set -g escape-time 4
set -g default-terminal "xterm-256color"
set-option -g detach-on-destroy off
set-option -g allow-rename off
set -g mouse on

### Window and Pane Indexing
set-option -g base-index 1
set-window-option -g pane-base-index 1

### Enable vi keys in copy and choose mode
set-window-option -g mode-keys vi

### Reload config
bind-key r source-file ~/.tmux.conf \; display "Config Reloaded!"
## Splits
unbind-key v
unbind-key h
bind-key M-j split-window -v    # horizontal split
bind-key M-h split-window -h    # vertical split

## Kill pane/window
unbind-key x
bind-key x kill-pane
bind-key X kill-window

## Resize Panes - Vim style
bind-key -n C-H resize-pane -L 2
bind-key -n C-J resize-pane -D 2
bind-key -n C-K resize-pane -U 2
bind-key -n C-L resize-pane -R 2

## Arrow Key Navigation
bind-key Up select-pane -U
bind-key Down select-pane -D
bind-key Left select-pane -L
bind-key Right select-pane -R

### Smart pane switching with Vim awareness
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n C-j if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n C-k if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n C-l if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'
bind-key -n M-\\ if-shell "$is_vim" 'send-keys C-\\' 'select-pane -l'

### Copy Mode
bind-key Escape copy-mode
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key M-v run "tmux set-buffer \"$(wl-copy)\""

### Sesh
bind-key a display-popup -E -w 40% "bash ~/.script/sss.sh"

set -g status on
set -g status-position top
set -g status-style "bg=default"
set -g status-justify absolute-centre
set -g window-status-current-style "bg=default fg=#6E93B1  "
set -g status-left "[#S]"
set -g status-left-length 30
set -g status-right ""
set -g status-left-style "fg=black bg=#6E93B1  "
set -g pane-border-style fg=colour240          # inactive pane border
set -g pane-active-border-style fg=#6E93B1    # active pane border
